export const INTERBANK_VAULT_ABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_finNovaSafe', type: 'address', internalType: 'address' },
      { name: '_cnbvViewPubKey', type: 'bytes32', internalType: 'bytes32' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'EIP712_NAME',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'EIP712_VERSION',
    inputs: [],
    outputs: [{ name: '', type: 'string', internalType: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'bankNonces',
    inputs: [{ name: '', type: 'address', internalType: 'address' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'cnbvViewPubKey',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'finNovaSafe',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTransfer',
    inputs: [{ name: 'transferId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [
      { name: '', type: 'bytes32', internalType: 'bytes32' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'bytes32', internalType: 'bytes32' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'uint8', internalType: 'enum InterbankVault.State' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getTransferState',
    inputs: [{ name: 'transferId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'uint8', internalType: 'enum InterbankVault.State' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'openTransfer',
    inputs: [
      { name: 'bank', type: 'address', internalType: 'address' },
      { name: 'beneficiary', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'commitment', type: 'bytes32', internalType: 'bytes32' },
      { name: 'bankNonce', type: 'uint256', internalType: 'uint256' },
      { name: 'expiry', type: 'uint256', internalType: 'uint256' },
      { name: 'v', type: 'uint8', internalType: 'uint8' },
      { name: 'r', type: 'bytes32', internalType: 'bytes32' },
      { name: 's', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'refund',
    inputs: [{ name: 'transferId', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'release',
    inputs: [
      { name: 'transferId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'to', type: 'address', internalType: 'address payable' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transfers',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [
      { name: 'transferId', type: 'bytes32', internalType: 'bytes32' },
      { name: 'bank', type: 'address', internalType: 'address' },
      { name: 'beneficiary', type: 'address', internalType: 'address' },
      { name: 'depositor', type: 'address', internalType: 'address payable' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'commitment', type: 'bytes32', internalType: 'bytes32' },
      { name: 'bankNonce', type: 'uint256', internalType: 'uint256' },
      { name: 'expiry', type: 'uint256', internalType: 'uint256' },
      { name: 'state', type: 'uint8', internalType: 'enum InterbankVault.State' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'event',
    name: 'TransferOpened',
    inputs: [
      { name: 'transferId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'bank', type: 'address', indexed: true, internalType: 'address' },
      { name: 'beneficiary', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'commitment', type: 'bytes32', indexed: false, internalType: 'bytes32' },
      { name: 'expiry', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TransferRefunded',
    inputs: [
      { name: 'transferId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TransferReleased',
    inputs: [
      { name: 'transferId', type: 'bytes32', indexed: true, internalType: 'bytes32' },
      { name: 'to', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'error',
    name: 'BeneficiaryMismatch',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'InvalidSignature',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'InvalidTransferState',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'NativeRefundFailed',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'NativeTransferFailed',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'NonceMismatch',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'NotDepositor',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'NotExpired',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'OnlyFinNovaSafe',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'TransferExpired',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'ValueMismatch',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'ZeroAmount',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'ZeroBank',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'ZeroBeneficiary',
    inputs: [],
    internalType: 'error',
  },
  {
    type: 'error',
    name: 'ZeroSafeAddress',
    inputs: [],
    internalType: 'error',
  },
] as const;